Repository aurorazilio/AMA-groupwork, pull requests merged in 2023-12, with the labels that each got.

#12 #7
  README.md
  backend/app/main.py
Labels: enhancement

#15 Hotfix Backend function
  backend/app/main.py
Labels: bug

#18 Yourprovider in frontend
  frontend/app/main.py
  frontend/app/templates/base.html
  frontend/app/templates/provider.html
Labels: enhancement

#29 update of provider section
  backend/app/main.py
  frontend/app/main.py
  frontend/app/templates/base.html
  frontend/app/templates/provider.html
Labels: enhancement

#31 tests lorenzo
  backend/tests/test_main.py
Labels: enhancement

#32 Integration of backend and frontend
  backend/app/main.py
  frontend/app/main.py
  frontend/app/templates/addresses.html
  frontend/app/templates/base.html
  frontend/app/templates/index.html
  frontend/app/templates/internal.html
Labels: enhancement

#35 Hotfix problem
  frontend/app/main.py
Labels: bug

#36 Frontend provider streetname
  frontend/app/main.py
  frontend/app/ricarica_colonnine_maps.csv
  frontend/app/templates/base.html
  frontend/app/templates/street_name1.html
Labels: enhancement

#39 Test charging stations given street name
  backend/app/main.py
  backend/tests/test_main.py
Labels: enhancement, test

#40 Integration of 3 tests and improvement of backend
  backend/app/main.py
  backend/tests/test_main.py
Labels: enhancement, test

#42 First restyling
  frontend/app/static/charging_station.jpg
  frontend/app/templates/base.html
Labels: enhancement

#45 Enhancement pep-8
  backend/app/main.py
  backend/tests/test_main.py
  frontend/app/main.py
Labels: enhancement

#47 Improvement - Aurora
  frontend/app/main.py
  frontend/app/templates/addresses.html
  frontend/app/templates/base.html
Labels: enhancement

#50 home_description_and_enhancement
  frontend/app/main.py
  frontend/app/templates/addresses.html
  frontend/app/templates/index.html
  frontend/app/templates/number_stations.html
  frontend/app/templates/socket_types.html
Labels: enhancement

#51 Frontend design
  frontend/app/templates/addresses.html
  frontend/app/templates/base.html
  frontend/app/templates/index.html
  frontend/app/templates/number_stations.html
  frontend/app/templates/provider.html
  frontend/app/templates/socket_types.html
  frontend/app/templates/street_name1.html
Labels: enhancement

#52 Synchronization of the responses of function
  backend/app/main.py
  backend/tests/test_main.py
  frontend/app/main.py
Labels: enhancement

#55 enhancement of the graphic
  backend/app/main.py
  frontend/app/ricarica_colonnine_maps.csv
  frontend/app/templates/number_stations.html
  frontend/app/templates/socket_types.html
Labels: enhancement

#57 adaptation of tests
  backend/app/main.py
  backend/tests/test_main.py
Labels: bug

#58 readme and basic enhancements
  README.md
  backend/app/main.py
  frontend/app/main.py
  frontend/app/templates/base.html
  frontend/app/templates/index.html
  frontend/app/templates/street_name1.html
Labels: enhancement

#59 Add improvement details
  frontend/app/templates/addresses.html
Labels: enhancement

#62 hotfix_providers_output
  frontend/app/templates/provider.html
Labels: bug

#63 hotfix_tests
  backend/tests/test_main.py
Labels: bug
